package cli

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

// shellQuote returns a shell-safe single-quoted string.
// Single quotes within the value are escaped as '\” (end quote, escaped quote, start quote).
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

const zshWrapper = `# ws — shell wrapper for workspace
# Generated by: workspace shell-init zsh
# Add to ~/.zshrc: eval "$(workspace shell-init zsh)"

ws() {
  case "${1:-}" in
    jump|j|lift|dock|mc)
      eval "$(command workspace "$@")"
      ;;
    *)
      command workspace "$@"
      ;;
  esac
}

`

func newShellInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "shell-init <shell>",
		Short: "Output shell setup (wrapper function + completions)",
		Long: `Outputs a shell script that defines the ws() wrapper function and
sets up tab completions. Source this in your shell's rc file:

  eval "$(workspace shell-init zsh)"`,
		Args:              cobra.ExactArgs(1),
		ValidArgs:         []string{"zsh"},
		ValidArgsFunction: cobra.NoFileCompletions,
		SilenceErrors:     true,
		SilenceUsage:      true,
		RunE: func(cmd *cobra.Command, args []string) error {
			shell := args[0]

			switch shell {
			case "zsh":
				return outputZshInit(cmd)
			default:
				return fmt.Errorf("unsupported shell %q (supported: zsh)", shell)
			}
		},
	}
}

func outputZshInit(cmd *cobra.Command) error {
	out := cmd.OutOrStdout()

	// Write the ws() wrapper function
	fmt.Fprint(out, zshWrapper)

	// Generate completions for workspace, then alias to ws
	var buf bytes.Buffer
	root := cmd.Root()
	if err := root.GenZshCompletion(&buf); err != nil {
		return fmt.Errorf("generating completions: %w", err)
	}
	fmt.Fprint(out, buf.String())
	fmt.Fprintln(out, "compdef _workspace ws")

	return nil
}
